---
# tasks file for ansible-role-nhc
#
 - name: template in nhc.conf
   template: src=nhc.conf.j2 dest=/etc/nhc/nhc.conf backup=yes mode=0644

 - name: template in extra nhc scripts
   template: src={{ item }} dest=/etc/nhc/scripts/{{ item }} backup=yes mode=0644
   with_items: "{{Â nhc_scripts }}"
   when: nhc_scripts.0 != ""
